### PR TITLE
Modernize for python 3 compatibility

### PR DESCRIPTION
**Pull request by Secrus**

### CODE REVIEW

**Review by kambie — APPROVED** [review]

**Comment by kambie** [comment]
@Secrus stupid question... how is this published/used in Monolith? Are we using direct link to this repo in requirements file?

**Comment by Secrus** [comment]
> @Secrus stupid question... how is this published/used in Monolith? Are we using direct link to this repo in requirements file?

More less. The requirements file points to a zip file (I presume built with setuptools) from GH releases. [here](https://github.com/beekpr/beekeeper/blob/dea4d6ead7fe717e3434546d5d1630db440c301c/requirements.txt#L28)

**Review by kshyk — APPROVED** [review]

**Comment by kshyk** [comment]
Unapproved as unit tests are not passing

**Review by kambie — CHANGES_REQUESTED** [review]
Let's fix unit tests

**Comment by Secrus** [comment]
image
Tested locally on Python 2 too, since GH Actions doesn't support Python 2 anymore.

**Review by kshyk — APPROVED** [review]

**Review by kambie — APPROVED** [review]
lgtm

**Pull request merged**
